main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('home/', views.home)
]

multiapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('main/', include('main.urls')),
    path('myapp/', include('myapp.urls')),
    path('secondapp/', include('secondapp.urls')),
    path('admin/', admin.site.urls),
]

myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path('home/', views.home, name="myapphome")
]

secondapp/urls.py
from django.urls import path
from secondapp import views

app_name = 'secondapp'

urlpatterns = [
    path('home/', views.home, name="secondapphome")
]

main/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models

# Create your models here.

secondapp/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,"main/index.html")

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request,"myapp/myapp_home.html")

secondapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return render(request,"secondapp/secondapp_home.html")

templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <H1>Main index Page</H1>
    <table>
        <tr>
            <td>
                <a href="{% url 'myapp:myapphome' %}">Myapp Home</a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'secondapp:secondapphome' %}">SecondApp Home</a>
            </td>
        </tr>
    </table>
</body>
</html>

templates/myapp/myapp_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Myapp Home</h1>
</body>
</html>

templates/secondapp/secondapp_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>SecondApp Home</h1>
</body>
</html>